# Generated by Django 5.1.15 on 2026-09-28 03:49

import apps.contracts.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('contract_number', models.CharField(db_index=True, default=apps.contracts.models.generate_contract_number, editable=False, help_text='Unique tracking identifier (e.g. CNT-20260928-8F2B1A)', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Contract title (e.g., Annual Chiller & HVAC Maintenance)', max_length=255)),
                ('start_date', models.DateField(db_index=True, help_text='Contract commencement date')),
                ('end_date', models.DateField(db_index=True, help_text='Contract expiration date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Current agreement status', max_length=20)),
                ('service_frequency', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly (Every Month)'), ('BI_MONTHLY', 'Bi-Monthly (Every 2 Months)'), ('QUARTERLY', 'Quarterly (Every 3 Months)'), ('HALF_YEARLY', 'Half-Yearly (Every 6 Months)'), ('ANNUALLY', 'Annually (Once a Year)')], default='QUARTERLY', help_text='Frequency of scheduled preventive maintenance visits', max_length=20)),
                ('total_visits_allowed', models.PositiveIntegerField(default=4, help_text='Total number of service visits included in the contract quota')),
                ('visits_used', models.PositiveIntegerField(default=0, help_text='Number of completed maintenance visits consumed')),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total monetary contract billing value', max_digits=12)),
                ('sla_response_hours', models.PositiveIntegerField(default=24, help_text='Guaranteed SLA emergency breakdown response time in hours')),
                ('next_scheduled_date', models.DateField(blank=True, db_index=True, help_text='Projected date for the next periodic preventive maintenance visit', null=True)),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Specific SLA clauses, warranty exclusions, or special terms')),
                ('termination_reason', models.TextField(blank=True, help_text='Mandatory justification note if contract is prematurely cancelled')),
                ('terminated_at', models.DateTimeField(blank=True, help_text='Timestamp when contract was terminated', null=True)),
                ('covered_services', models.ManyToManyField(blank=True, help_text='Service types included in this maintenance contract', related_name='contracts', to='services.servicetype')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who created the contract record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Client organization holding the maintenance agreement', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.customer')),
                ('service_location', models.ForeignKey(help_text='Physical facility covered under this contract', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='customers.servicelocation')),
            ],
            options={
                'verbose_name': 'Service Contract',
                'verbose_name_plural': 'Service Contracts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
