# Generated by Django 5.1.15 on 2026-09-23 09:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('request_number', models.CharField(db_index=True, editable=False, help_text='Human-readable tracking identifier (e.g. SR-20260923-A1B2C3)', max_length=32, unique=True)),
                ('title', models.CharField(help_text='Concise summary of the reported issue', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of symptoms, fault codes, or equipment')),
                ('priority', models.CharField(choices=[('LOW', 'Low (Routine / Maintenance)'), ('MEDIUM', 'Medium (Standard Issue)'), ('HIGH', 'High (Urgent / Business Impaired)'), ('CRITICAL', 'Critical (Emergency / Facility Down)')], db_index=True, default='MEDIUM', help_text='Urgency level determining automated SLA response and resolution deadlines', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New / Submitted'), ('REVIEWED', 'Reviewed / Triaged'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', help_text='Current state in the request lifecycle state machine', max_length=20)),
                ('preferred_date', models.DateField(blank=True, help_text="Customer's requested service date", null=True)),
                ('preferred_time_slot', models.CharField(blank=True, help_text="Preferred time window (e.g. '09:00 - 13:00' or 'Afternoon')", max_length=50)),
                ('sla_response_due_at', models.DateTimeField(blank=True, help_text='Calculated deadline for dispatcher review/first response', null=True)),
                ('sla_resolution_due_at', models.DateTimeField(blank=True, help_text='Calculated deadline for field resolution', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('dispatcher_notes', models.TextField(blank=True, help_text='Internal dispatcher/scheduling notes (not visible to customer)')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason recorded if request was cancelled')),
                ('customer', models.ForeignKey(help_text='Customer company or entity raising the service ticket', on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='customers.customer')),
                ('reported_by', models.ForeignKey(blank=True, help_text='User who submitted this service request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_service_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Dispatcher or manager who triaged this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_requests', to=settings.AUTH_USER_MODEL)),
                ('service_location', models.ForeignKey(help_text='Physical branch or job site where service is required', on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='customers.servicelocation')),
                ('service_type', models.ForeignKey(blank=True, help_text='Primary category of service requested (HVAC, Electrical, Plumbing, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='services.servicetype')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('file', models.FileField(help_text='Uploaded photo or document', upload_to='service_requests/attachments/%Y/%m/')),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_type', models.CharField(blank=True, help_text='MIME type or file extension', max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, help_text='Size of the file in bytes')),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g. 'Fault display error E-04' or 'Water leak on pipe 2')", max_length=255)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(help_text='Service request this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='service_requests.servicerequest')),
            ],
            options={
                'verbose_name': 'Request Attachment',
                'verbose_name_plural': 'Request Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', 'status'], name='service_req_custome_71a400_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['priority', 'status'], name='service_req_priorit_b187ce_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['sla_resolution_due_at'], name='service_req_sla_res_3afc76_idx'),
        ),
    ]
