# Generated by Django 5.1.15 on 2026-09-22 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company name for corporate accounts', max_length=200)),
                ('primary_contact_name', models.CharField(help_text='Full name of the primary contact person', max_length=150)),
                ('email', models.EmailField(db_index=True, help_text='Billing and primary notification email', max_length=254)),
                ('phone', models.CharField(db_index=True, help_text='Primary contact phone number', max_length=20)),
                ('billing_address', models.TextField(blank=True, help_text='Official billing address for invoice generation')),
                ('tax_id', models.CharField(blank=True, help_text='GST / Tax Identification Number', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Internal account management notes')),
                ('user', models.OneToOneField(blank=True, help_text='Optional linked portal login user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('location_name', models.CharField(help_text='Descriptive title e.g. Main Plant, Downtown Office, Home', max_length=150)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(db_index=True, max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Latitude for routing', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='GPS Longitude for routing', max_digits=9, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='On-site contact person if different from customer', max_length=150)),
                ('contact_phone', models.CharField(blank=True, help_text='On-site phone number', max_length=20)),
                ('access_instructions', models.TextField(blank=True, help_text='Gate codes, security clearance, parking instructions')),
                ('is_primary', models.BooleanField(default=False, help_text='Flag indicating the primary or headquarters location')),
                ('customer', models.ForeignKey(help_text='Customer who owns or manages this site', on_delete=django.db.models.deletion.CASCADE, related_name='service_locations', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Service Location',
                'verbose_name_plural': 'Service Locations',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email', 'phone'], name='customers_c_email_bfbcf0_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company_name'], name='customers_c_company_2610e7_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelocation',
            index=models.Index(fields=['customer', 'city'], name='customers_s_custome_ef166c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelocation',
            index=models.Index(fields=['postal_code'], name='customers_s_postal__972721_idx'),
        ),
    ]
