# Generated by Django 5.1.15 on 2026-09-28 05:02

import apps.billing.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('work_orders', '0003_workorder_is_preventive_maintenance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('invoice_number', models.CharField(db_index=True, default=apps.billing.models.generate_invoice_number, editable=False, help_text='Unique tracking invoice number (e.g. INV-20260928-8F2B1A)', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Current state of invoice collection', max_length=20)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date invoice was issued to customer')),
                ('due_date', models.DateField(blank=True, help_text='Payment due date', null=True)),
                ('labor_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total billable labor charge (hours × rate)', max_digits=12)),
                ('parts_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total spare parts and consumables charge', max_digits=12)),
                ('service_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base standard service fee (0.00 if covered under AMC contract)', max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Goodwill, promotional, or contract discount applied', max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), help_text='Tax percentage (e.g. 18.00 for 18% GST)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculated GST / tax amount', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final net payable amount (Subtotal + Tax)', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Invoice remarks or payment instructions')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Mandatory note if invoice is voided or cancelled')),
                ('created_by', models.ForeignKey(blank=True, help_text='Staff member who generated this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer account billed', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('work_order', models.ForeignKey(help_text='Work order billed', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('payment_number', models.CharField(db_index=True, default=apps.billing.models.generate_payment_number, editable=False, help_text='Unique receipt tracking number (e.g. PAY-20260928-4E7A2C)', max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount remitted in this transaction', max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI / QR Code'), ('CREDIT_CARD', 'Credit / Debit Card'), ('CHEQUE', 'Cheque / Demand Draft')], default='BANK_TRANSFER', help_text='Payment instrument used by customer', max_length=20)),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'Success'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], db_index=True, default='SUCCESS', help_text='Payment execution status', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, help_text='Bank UTR number, UPI transaction ID, or Cheque number', max_length=100)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate, help_text='Date remittance was credited')),
                ('notes', models.TextField(blank=True, help_text='Payer details, bank branch, or internal cashier notes')),
                ('invoice', models.ForeignKey(help_text='Invoice this payment is applied against', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Staff member or cashier who registered this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
