# Generated by Django 5.1.15 on 2026-09-29 03:53

import apps.attachments.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('file', models.FileField(help_text='Binary file stored on disk or storage bucket', upload_to=apps.attachments.models.attachment_upload_path)),
                ('file_name', models.CharField(help_text="Original uploaded filename (e.g., 'chiller_pressure_log.pdf')", max_length=255)),
                ('file_type', models.CharField(blank=True, help_text="Detected MIME content-type (e.g., 'image/jpeg', 'application/pdf')", max_length=100)),
                ('file_size_bytes', models.PositiveIntegerField(default=0, help_text='Physical file size in bytes')),
                ('attachment_type', models.CharField(choices=[('BEFORE_SERVICE', 'Before Service Photo'), ('AFTER_SERVICE', 'After Service Photo'), ('COMPLETION_EVIDENCE', 'Completion Evidence / Sign-off'), ('DIAGNOSTIC_REPORT', 'Diagnostic / Inspection Report'), ('PAYMENT_RECEIPT', 'Payment Receipt / Deposit Slip'), ('CONTRACT_DOCUMENT', 'Contract / Agreement Document'), ('CUSTOMER_DOCUMENT', 'Customer Identity / KYC Document'), ('GENERAL', 'General Attachment')], db_index=True, default='GENERAL', help_text='Operational classification of this document', max_length=30)),
                ('description', models.CharField(blank=True, help_text='Optional remarks, caption, or diagnosis note', max_length=255)),
                ('related_entity_type', models.CharField(choices=[('work_order', 'Work Order'), ('service_request', 'Service Request'), ('customer', 'Customer'), ('contract', 'Service Contract'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('general', 'General')], db_index=True, default='general', help_text='Domain model category this file links to', max_length=50)),
                ('related_entity_id', models.UUIDField(db_index=True, help_text='UUID primary key of the associated entity instance')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User account that uploaded this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['related_entity_type', 'related_entity_id'], name='attachments_related_ea6538_idx'), models.Index(fields=['uploaded_by', '-created_at'], name='attachments_uploade_368c67_idx'), models.Index(fields=['attachment_type', '-created_at'], name='attachments_attachm_1ad7ce_idx')],
            },
        ),
    ]
