# Generated by Django 5.1.15 on 2026-09-22 04:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.SlugField(help_text='Short unique identifier code e.g. HVAC, ELEC, PLUMB', unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.SlugField(help_text='Unique SKU/Service identifier e.g. AC-COMPRESSOR-REPAIR', unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Base standard service fee in currency units (INR)', max_digits=10)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected job duration in minutes for scheduling calculations')),
                ('required_skill', models.CharField(blank=True, help_text='Matching skill requirement for technician dispatching e.g. HVAC, Electrical', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(help_text='Parent category (Protected from deletion if active services exist)', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='services_se_categor_956455_idx'), models.Index(fields=['required_skill'], name='services_se_require_648636_idx')],
            },
        ),
    ]
