# Generated by Django 5.1.15 on 2026-09-24 03:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('service_requests', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('work_order_number', models.CharField(db_index=True, editable=False, help_text='Human-readable tracking identifier (e.g. WO-20260924-A1B2C3)', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft / Unassigned'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Current state in the work order lifecycle state machine', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', help_text='Urgency level for scheduling prioritization', max_length=20)),
                ('title', models.CharField(help_text='Short title of the job card', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed problem summary and scope of work')),
                ('job_instructions', models.TextField(blank=True, help_text='Technical notes, access codes, PPE requirements, safety precautions')),
                ('scheduled_start', models.DateTimeField(blank=True, help_text='Scheduled job start time', null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, help_text='Scheduled job completion time', null=True)),
                ('actual_start', models.DateTimeField(blank=True, help_text='Timestamp when technician clicked start', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Timestamp when job was finished', null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=60, help_text='Expected duration in minutes for scheduling planning')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual billable labor hours logged', max_digits=5)),
                ('hold_reason', models.TextField(blank=True, help_text='Explanation if job is put ON_HOLD')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Explanation if job is CANCELLED')),
                ('assigned_technician', models.ForeignKey(blank=True, help_text='Field technician responsible for executing the job (must have role=TECHNICIAN)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer company or account being serviced', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='customers.customer')),
                ('service_location', models.ForeignKey(help_text='Job site where the technician must report', on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='customers.servicelocation')),
                ('service_request', models.ForeignKey(blank=True, help_text='Parent service ticket this work order was generated from (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='service_requests.servicerequest')),
                ('service_type', models.ForeignKey(blank=True, help_text='Specific service SKU / maintenance task being performed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='services.servicetype')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('from_status', models.CharField(max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_history_entries', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(help_text='Work order this audit log belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work Order History',
                'verbose_name_plural': 'Work Order History',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['customer', 'status'], name='work_orders_custome_45985b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_technician', 'status'], name='work_orders_assigne_503918_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_start', 'scheduled_end'], name='work_orders_schedul_4b90b8_idx'),
        ),
    ]
