# Generated by Django 5.1.15 on 2026-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='arrived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when technician reached customer site', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_feedback',
            field=models.TextField(blank=True, help_text='Customer remarks or feedback'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Customer satisfaction rating from 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_signature',
            field=models.TextField(blank=True, help_text='Base64 encoded digital signature image string'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Explanation if job is REJECTED by technician'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_summary',
            field=models.TextField(blank=True, help_text='Technical summary of diagnosis, repair, or service rendered'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when digital signature was captured', null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='signed_by_name',
            field=models.CharField(blank=True, help_text='Name of client/representative who signed', max_length=255),
        ),
        migrations.AddField(
            model_name='workorder',
            name='travel_started_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when technician started traveling to site', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft / Unassigned'), ('ASSIGNED', 'Assigned'), ('SCHEDULED', 'Scheduled'), ('ACCEPTED', 'Accepted'), ('TRAVELING', 'Traveling'), ('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='Current state in the work order lifecycle state machine', max_length=20),
        ),
    ]
