# Generated by Django 5.1.15 on 2026-09-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('work_orders', '0002_workorder_arrived_at_workorder_customer_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_preventive_maintenance',
            field=models.BooleanField(db_index=True, default=False, help_text='Flag indicating scheduled periodic preventive maintenance under a contract'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_contract',
            field=models.ForeignKey(blank=True, help_text='Parent maintenance contract (if this is an AMC / preventive visit)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='contracts.servicecontract'),
        ),
    ]
