# Generated by Django 5.1.15 on 2026-09-24 10:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0002_workorder_arrived_at_workorder_customer_feedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('sku', models.CharField(db_index=True, help_text='Unique Stock Keeping Unit (e.g., COMP-R410A-10KG)', max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, help_text='Display name of the part', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed technical specs or usage instructions')),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('HVAC', 'HVAC & Refrigeration'), ('PLUMBING', 'Plumbing'), ('CONSUMABLE', 'Consumables & Fasteners'), ('TOOLS', 'Tools & Equipment'), ('OTHER', 'Other')], db_index=True, default='OTHER', help_text='Domain classification for parts catalog', max_length=32)),
                ('unit_of_measure', models.CharField(choices=[('PIECE', 'Piece / Unit'), ('KG', 'Kilogram (kg)'), ('METER', 'Meter (m)'), ('LITER', 'Liter (L)'), ('SET', 'Set'), ('BOX', 'Box / Pack'), ('ROLL', 'Roll')], default='PIECE', help_text='Inventory measurement unit', max_length=20)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal procurement / cost price', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Standard customer billing unit price', max_digits=12)),
                ('reorder_threshold', models.PositiveIntegerField(default=5, help_text='Minimum aggregate stock level before triggering low-stock alerts')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this part is available for active dispatch & requisition')),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'ordering': ['sku'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique warehouse code (e.g. WH-DEL-01)', max_length=32, unique=True)),
                ('name', models.CharField(help_text='Human-readable facility name (e.g., Delhi Central Hub)', max_length=255)),
                ('address', models.TextField(blank=True, help_text='Street address / location of the facility')),
                ('city', models.CharField(db_index=True, help_text='City / operational hub', max_length=100)),
                ('is_primary', models.BooleanField(default=False, help_text='Flag indicating the primary regional distribution depot')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Flag indicating if the facility is operational')),
                ('manager', models.ForeignKey(blank=True, help_text='Facility manager or supervisor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('transaction_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt (Stock Inward)'), ('TRANSFER_TO_VAN', 'Transfer to Technician Van'), ('RETURN_TO_WAREHOUSE', 'Return to Warehouse'), ('RESERVED_FOR_JOB', 'Reserved for Work Order'), ('RELEASED_FROM_JOB', 'Reservation Released'), ('CONSUMED_ON_JOB', 'Consumed on Work Order'), ('RETURNED_FROM_JOB', 'Returned from Work Order'), ('ADJUSTMENT', 'Inventory Adjustment / Reconciliation')], db_index=True, help_text='Classification of the inventory movement', max_length=32)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units moved, consumed, or adjusted')),
                ('from_location', models.CharField(blank=True, help_text="Source description (e.g. 'Warehouse: WH-DEL-01' or 'Technician Van: Ramesh')", max_length=100)),
                ('to_location', models.CharField(blank=True, help_text="Destination description (e.g. 'Work Order: WO-20260924-62B1E0')", max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Reason, purchase order reference, or audit notes')),
                ('from_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_outward_transactions', to=settings.AUTH_USER_MODEL)),
                ('performed_by', models.ForeignKey(blank=True, help_text='User who initiated or authorized this stock operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('to_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_inward_transactions', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(blank=True, help_text='Associated work order (if consumed or reserved on a job)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='work_orders.workorder')),
                ('part', models.ForeignKey(help_text='Part affected by this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='inventory.part')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outward_transactions', to='inventory.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inward_transactions', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('source_location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse Depot'), ('TECHNICIAN_VAN', 'Technician Mobile Van')], default='TECHNICIAN_VAN', help_text='Source inventory location where the part was deducted from', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity consumed or reserved on the job')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Locked billing unit price at the time of consumption', max_digits=12)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONSUMED', 'Consumed'), ('RETURNED', 'Returned')], db_index=True, default='CONSUMED', help_text='Consumption status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Field notes or installation remarks')),
                ('part', models.ForeignKey(help_text='Part consumed or reserved', on_delete=django.db.models.deletion.PROTECT, related_name='work_order_usages', to='inventory.part')),
                ('technician', models.ForeignKey(blank=True, help_text='Technician van where the part was deducted from', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, help_text='Source warehouse (if deducted directly from warehouse)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
                ('work_order', models.ForeignKey(help_text='Work order where the part was used', on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Work Order Part',
                'verbose_name_plural': 'Work Order Parts',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('location_type', models.CharField(choices=[('WAREHOUSE', 'Warehouse Depot'), ('TECHNICIAN_VAN', 'Technician Mobile Van')], db_index=True, help_text='Type of storage location', max_length=20)),
                ('quantity_on_hand', models.IntegerField(default=0, help_text='Physical count of items currently in this location')),
                ('quantity_reserved', models.IntegerField(default=0, help_text='Count of items reserved for upcoming scheduled work orders')),
                ('part', models.ForeignKey(help_text='Catalog part being stocked', on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.part')),
                ('technician', models.ForeignKey(blank=True, help_text='Technician holding this van stock (if location_type == TECHNICIAN_VAN)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='van_stock_items', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse facility (if location_type == WAREHOUSE)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Item',
                'verbose_name_plural': 'Stock Items',
                'ordering': ['part__sku'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('part', 'warehouse'), name='unique_part_warehouse_stock'), models.UniqueConstraint(condition=models.Q(('technician__isnull', False)), fields=('part', 'technician'), name='unique_part_technician_stock')],
            },
        ),
    ]
