# Generated by Django 5.1.15 on 2026-09-24 05:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleOverrideLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('conflict_details', models.JSONField(default=dict, help_text='Snapshot of the conflicts detected prior to override')),
                ('override_reason', models.TextField(help_text='Mandatory business justification for forcing the scheduling override')),
                ('overridden_by', models.ForeignKey(help_text='Dispatcher or administrator who authorized the override', on_delete=django.db.models.deletion.CASCADE, related_name='authorized_overrides', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(help_text='Technician who received the conflicting schedule', on_delete=django.db.models.deletion.CASCADE, related_name='technician_overrides', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(help_text='Work order scheduled with an intentional override', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_overrides', to='work_orders.workorder')),
            ],
            options={
                'verbose_name': 'Schedule Override Log',
                'verbose_name_plural': 'Schedule Override Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianLeave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('leave_type', models.CharField(choices=[('VACATION', 'Vacation / Paid Leave'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('TRAINING', 'Training / Certification'), ('PERSONAL', 'Personal Leave')], default='VACATION', max_length=20)),
                ('start_date', models.DateField(help_text='First date of leave (inclusive)')),
                ('end_date', models.DateField(help_text='Last date of leave (inclusive)')),
                ('reason', models.TextField(blank=True, help_text='Optional description for the leave request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='APPROVED', max_length=20)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_technician_leaves', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(help_text='Technician taking time off', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Leave',
                'verbose_name_plural': 'Technician Leaves',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['technician', 'status'], name='scheduling__technic_0dd5fb_idx'), models.Index(fields=['start_date', 'end_date'], name='scheduling__start_d_b99e30_idx')],
            },
        ),
    ]
