# Generated by Django 5.1.15 on 2026-09-28 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUIDv4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Flag indicating whether this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when this record was soft-deleted', null=True)),
                ('title', models.CharField(help_text='Short alert headline or subject.', max_length=255)),
                ('message', models.TextField(help_text='Detailed notification body or action context.')),
                ('notification_type', models.CharField(choices=[('WORK_ORDER_ASSIGNED', 'Work Order Assigned'), ('WORK_ORDER_STATUS_CHANGED', 'Work Order Status Changed'), ('WORK_ORDER_COMPLETED', 'Work Order Completed'), ('SERVICE_REQUEST_CREATED', 'Service Request Created'), ('INVOICE_GENERATED', 'Invoice Generated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('CONTRACT_EXPIRING', 'Contract Expiring'), ('GENERAL', 'General Notification')], db_index=True, default='GENERAL', help_text='Category of business event triggering this notification.', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', help_text='Urgency ranking of the notification.', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the recipient has acknowledged/read this notification.')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when the notification was marked as read.', null=True)),
                ('related_entity_type', models.CharField(blank=True, help_text="Name of the associated model entity (e.g., 'work_order', 'invoice', 'part').", max_length=50)),
                ('related_entity_id', models.UUIDField(blank=True, help_text='UUID primary key of the associated model entity.', null=True)),
                ('recipient', models.ForeignKey(help_text='Target user receiving this notification alert.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx')],
            },
        ),
    ]
