# Generated by Django 5.1.15 on 2026-09-29 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUIDv4 identifier for the audit event', primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Cached email of the actor (retained even if user is deleted)', max_length=255)),
                ('actor_role', models.CharField(blank=True, help_text='Cached role of the actor at the moment of the action', max_length=50)),
                ('action', models.CharField(choices=[('WORK_ORDER_CREATED', 'Work Order Created'), ('WORK_ORDER_ASSIGNED', 'Work Order Assigned'), ('WORK_ORDER_STATUS_CHANGED', 'Work Order Status Changed'), ('WORK_ORDER_RESCHEDULED', 'Work Order Rescheduled'), ('SERVICE_REQUEST_CREATED', 'Service Request Created'), ('SERVICE_REQUEST_REVIEWED', 'Service Request Reviewed'), ('SERVICE_REQUEST_CANCELLED', 'Service Request Cancelled'), ('INVOICE_GENERATED', 'Invoice Generated'), ('INVOICE_ISSUED', 'Invoice Issued'), ('INVOICE_CANCELLED', 'Invoice Cancelled'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('STOCK_ADJUSTED', 'Stock Quantity Adjusted'), ('PARTS_TRANSFERRED', 'Parts Transferred'), ('CONTRACT_ACTIVATED', 'Service Contract Activated'), ('CONTRACT_TERMINATED', 'Service Contract Terminated'), ('USER_CREATED', 'User Account Created'), ('USER_ROLE_CHANGED', 'User Role Changed'), ('USER_DEACTIVATED', 'User Deactivated'), ('GENERAL_ACTION', 'General System Action')], db_index=True, help_text='Formal business action classification', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Human-readable summary of the event', max_length=255)),
                ('entity_type', models.CharField(db_index=True, help_text="Target domain model name (e.g., 'work_order', 'invoice', 'stock_item')", max_length=50)),
                ('entity_id', models.UUIDField(db_index=True, help_text='Primary key UUID of the modified entity')),
                ('entity_repr', models.CharField(blank=True, help_text="Human-readable business identifier (e.g., 'WO-20260928-CF97F4')", max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Structured before/after diff of field modifications: {'field': {'old': ..., 'new': ...}}")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Remote IP address of the client making the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client User-Agent string for security auditing')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Exact UTC timestamp when the action occurred (immutable)')),
                ('actor', models.ForeignKey(blank=True, help_text='User who initiated or authorized this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_logs__entity__f2c7b5_idx'), models.Index(fields=['actor', '-created_at'], name='audit_logs__actor_i_bca6af_idx'), models.Index(fields=['action', '-created_at'], name='audit_logs__action_7c186a_idx')],
            },
        ),
    ]
